-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 14:45:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usedPhones
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `usedPhones` ;

-- -----------------------------------------------------
-- Schema usedPhones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usedPhones` DEFAULT CHARACTER SET utf8 ;
USE `usedPhones` ;

-- -----------------------------------------------------
-- Table `usedPhones`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usedPhones`.`Account` ;

CREATE TABLE IF NOT EXISTS `usedPhones`.`Account` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isVerified` TINYINT(1) UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
  `otp` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usedPhones`.`Phone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usedPhones`.`Phone` ;

CREATE TABLE IF NOT EXISTS `usedPhones`.`Phone` (
  `brand` VARCHAR(20) NOT NULL,
  `model` VARCHAR(20) NOT NULL,
  `color` VARCHAR(20) NOT NULL,
  `ramSize` INT UNSIGNED NOT NULL,
  `cores` INT UNSIGNED NOT NULL,
  `storageSize` INT UNSIGNED NOT NULL,
  `osVersion` VARCHAR(20) NOT NULL,
  `releaseDate` DATE NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `image` LONGBLOB NULL,
  `Account_username` VARCHAR(20) NOT NULL,
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Account_username`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  CONSTRAINT `fk_Phone_Account`
    FOREIGN KEY (`Account_username`)
    REFERENCES `usedPhones`.`Account` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `usedPhones`.`Account`
-- -----------------------------------------------------
START TRANSACTION;
USE `usedPhones`;
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('gkefas', '12345678', 'gkefas@gmail.com', 1, '12311');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('maria', '123456789', 'maria@gmail.com', 1, '32213');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('nikos', '123432134', 'nikos@gmail.com', 1, '43243');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('aggelos', '124355667', 'aggelos@gmail.com', 1, '32434');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('mixalis', '1241241132', 'mixalis@gmail.com', 1, '34124');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('nikoleta', '1234123413', 'nikoleta@gmail.com', 1, '22341');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('fotis', 'fotis134123', 'fotis@gmail.com', 1, '12341');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('vasiliki', 'vasw122212', 'vasiliki@gmail.com', 1, '12413');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('xristos', 'xristos12312', 'xristos@gmail.com', 1, '13122');
INSERT INTO `usedPhones`.`Account` (`username`, `password`, `email`, `isVerified`, `otp`) VALUES ('mpamphs', 'mpamphs14312', 'mpamphs@gmail.com', 1, '12231');

COMMIT;


-- -----------------------------------------------------
-- Data for table `usedPhones`.`Phone`
-- -----------------------------------------------------
START TRANSACTION;
USE `usedPhones`;
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Samsung', 'Galaxy A52s', 'black', 16, 6, 256, '16.2', '18-03-2021', 359, 'contract : 6973181642', NULL, 'gkefas', 1);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Iphone', '15 Pro Max', 'white', 16, 4, 256, 'iOS 17.2x', '22-05-2023', 1249, 'contract : 6983145671', NULL, 'maria', 2);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Huawei', 'P40', 'Silver frost', 8, 8, 128, '16.2', '05-11-2022', 569, 'contract : 6924578122', NULL, 'nikos', 3);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Samsung', 'Galaxy S22', 'black', 8, 8, 512, '18.2', '11-03-2022', 650, 'contract : 697 462 3495', NULL, 'aggelos', 4);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Xiaomi', 'Redmi Note 13 Pro', 'black', 12, 6, 256, '16.2', '05-08-2021', 290, 'contract : 698 314 1533', NULL, 'mixalis', 5);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Iphone', '13', 'blue', 12, 8, 256, 'iOS 17.2x', '06-04-2021', 560, 'contract : 694 221 4532', NULL, 'nikoleta', 6);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Huawei', 'Nova 10', 'silver', 8, 6, 128, '17', '22-08-2022', 390, 'contract : 693 421 9953', NULL, 'fotis', 7);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Realme', 'C55', 'Rainy Night', 8, 4, 256, '16.8', '22-05-2021', 130, 'contract : 693 243 9963', NULL, 'xristos', 8);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Oukitel', 'WP22', 'black', 8, 6, 256, '17', '04-11-2021', 190, 'contract : 694 953 7224', NULL, 'mpamphs', 9);
INSERT INTO `usedPhones`.`Phone` (`brand`, `model`, `color`, `ramSize`, `cores`, `storageSize`, `osVersion`, `releaseDate`, `price`, `description`, `image`, `Account_username`, `id`) VALUES ('Samsung', 'Galaxy S24 Ultra', 'Titanium Black', 12, 12, 1024, '19', '22-05-2023', 1260, 'contract : 694 234 1243', NULL, 'vasiliki', 10);

COMMIT;

